// This file is @generated by prost-build.
/// Client represents an OAuth2 client.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Client {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub secret: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub redirect_uris: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub trusted_peers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "5")]
    pub public: bool,
    #[prost(string, tag = "6")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub logo_url: ::prost::alloc::string::String,
}
/// CreateClientReq is a request to make a client.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateClientReq {
    #[prost(message, optional, tag = "1")]
    pub client: ::core::option::Option<Client>,
}
/// CreateClientResp returns the response from creating a client.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateClientResp {
    #[prost(bool, tag = "1")]
    pub already_exists: bool,
    #[prost(message, optional, tag = "2")]
    pub client: ::core::option::Option<Client>,
}
/// DeleteClientReq is a request to delete a client.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteClientReq {
    /// The ID of the client.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
/// DeleteClientResp determines if the client is deleted successfully.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteClientResp {
    #[prost(bool, tag = "1")]
    pub not_found: bool,
}
/// UpdateClientReq is a request to update an existing client.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateClientReq {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub redirect_uris: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub trusted_peers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub logo_url: ::prost::alloc::string::String,
}
/// UpdateClientResp returns the response from updating a client.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateClientResp {
    #[prost(bool, tag = "1")]
    pub not_found: bool,
}
/// Password is an email for password mapping managed by the storage.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Password {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    /// Currently we do not accept plain text passwords. Could be added in the future.
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub user_id: ::prost::alloc::string::String,
}
/// CreatePasswordReq is a request to make a password.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreatePasswordReq {
    #[prost(message, optional, tag = "1")]
    pub password: ::core::option::Option<Password>,
}
/// CreatePasswordResp returns the response from creating a password.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreatePasswordResp {
    #[prost(bool, tag = "1")]
    pub already_exists: bool,
}
/// UpdatePasswordReq is a request to modify an existing password.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdatePasswordReq {
    /// The email used to lookup the password. This field cannot be modified.
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub new_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub new_username: ::prost::alloc::string::String,
}
/// UpdatePasswordResp returns the response from modifying an existing password.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdatePasswordResp {
    #[prost(bool, tag = "1")]
    pub not_found: bool,
}
/// DeletePasswordReq is a request to delete a password.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeletePasswordReq {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
}
/// DeletePasswordResp returns the response from deleting a password.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeletePasswordResp {
    #[prost(bool, tag = "1")]
    pub not_found: bool,
}
/// ListPasswordReq is a request to enumerate passwords.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListPasswordReq {}
/// ListPasswordResp returns a list of passwords.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPasswordResp {
    #[prost(message, repeated, tag = "1")]
    pub passwords: ::prost::alloc::vec::Vec<Password>,
}
/// VerifyPasswordReq is a request to verify the user's password.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyPasswordReq {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
/// VerifyPasswordResp returns the result of password verification.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyPasswordResp {
    #[prost(bool, tag = "1")]
    pub verified: bool,
    #[prost(bool, tag = "2")]
    pub not_found: bool,
}
/// Connector is a strategy used by Dex for authenticating users
/// against another identity provider.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Connector {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// Config holds connector specific configuration.
    /// The field is stored as a JSON document.
    #[prost(bytes = "vec", tag = "4")]
    pub config: ::prost::alloc::vec::Vec<u8>,
}
/// CreateConnectorReq is a request to create a connector.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateConnectorReq {
    #[prost(message, optional, tag = "1")]
    pub connector: ::core::option::Option<Connector>,
}
/// CreateConnectorResp is a response from creating a connector.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateConnectorResp {
    #[prost(bool, tag = "1")]
    pub already_exists: bool,
}
/// UpdateConnectorReq is a request to update a connector.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateConnectorReq {
    /// The ID of the connector to update.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// The new values of the connector.
    #[prost(message, optional, tag = "2")]
    pub new_connector: ::core::option::Option<Connector>,
}
/// UpdateConnectorResp is a response from updating a connector.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateConnectorResp {
    #[prost(bool, tag = "1")]
    pub not_found: bool,
}
/// DeleteConnectorReq is a request to delete a connector.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteConnectorReq {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
/// DeleteConnectorResp is a response from deleting a connector.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteConnectorResp {
    #[prost(bool, tag = "1")]
    pub not_found: bool,
}
/// ListConnectorReq is a request to enumerate connectors.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListConnectorReq {}
/// ListConnectorResp is a response listing connectors.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListConnectorResp {
    #[prost(message, repeated, tag = "1")]
    pub connectors: ::prost::alloc::vec::Vec<Connector>,
}
/// VersionReq is a request to fetch version info.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VersionReq {}
/// VersionResp holds the version info of components.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VersionResp {
    #[prost(string, tag = "1")]
    pub server: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub api: i32,
}
/// RefreshTokenRef contains the metadata for a refresh token that is managed by the storage.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshTokenRef {
    /// ID of the refresh token.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub created_at: i64,
    #[prost(int64, tag = "6")]
    pub last_used: i64,
}
/// ListRefreshReq is a request to list refresh tokens for a user.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRefreshReq {
    /// The user to list the tokens for.
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// ListRefreshResp is a response containing the refresh tokens for a user.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRefreshResp {
    #[prost(message, repeated, tag = "1")]
    pub refresh_tokens: ::prost::alloc::vec::Vec<RefreshTokenRef>,
}
/// RevokeRefreshReq is a request to revoke the refresh token of the user-client pair.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeRefreshReq {
    /// The user id of the token to revoke.
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// The client id of the token to revoke.
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
}
/// RevokeRefreshResp is a response to revoking the refresh token.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeRefreshResp {
    /// Set to true if refresh token was not found in storage.
    #[prost(bool, tag = "1")]
    pub not_found: bool,
}
/// Generated client implementations.
pub mod dex_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Dex represents the dex gRPC service.
    #[derive(Debug, Clone)]
    pub struct DexClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl DexClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> DexClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> DexClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            DexClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// CreateClient creates a client.
        pub async fn create_client(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateClientReq>,
        ) -> std::result::Result<
            tonic::Response<super::CreateClientResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/CreateClient");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "CreateClient"));
            self.inner.unary(req, path, codec).await
        }
        /// UpdateClient updates an existing client.
        pub async fn update_client(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateClientReq>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateClientResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/UpdateClient");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "UpdateClient"));
            self.inner.unary(req, path, codec).await
        }
        /// DeleteClient deletes the provided client.
        pub async fn delete_client(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteClientReq>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteClientResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/DeleteClient");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "DeleteClient"));
            self.inner.unary(req, path, codec).await
        }
        /// CreatePassword creates a password.
        pub async fn create_password(
            &mut self,
            request: impl tonic::IntoRequest<super::CreatePasswordReq>,
        ) -> std::result::Result<
            tonic::Response<super::CreatePasswordResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/CreatePassword");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "CreatePassword"));
            self.inner.unary(req, path, codec).await
        }
        /// UpdatePassword modifies existing password.
        pub async fn update_password(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdatePasswordReq>,
        ) -> std::result::Result<
            tonic::Response<super::UpdatePasswordResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/UpdatePassword");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "UpdatePassword"));
            self.inner.unary(req, path, codec).await
        }
        /// DeletePassword deletes the password.
        pub async fn delete_password(
            &mut self,
            request: impl tonic::IntoRequest<super::DeletePasswordReq>,
        ) -> std::result::Result<
            tonic::Response<super::DeletePasswordResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/DeletePassword");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "DeletePassword"));
            self.inner.unary(req, path, codec).await
        }
        /// ListPassword lists all password entries.
        pub async fn list_passwords(
            &mut self,
            request: impl tonic::IntoRequest<super::ListPasswordReq>,
        ) -> std::result::Result<
            tonic::Response<super::ListPasswordResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/ListPasswords");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "ListPasswords"));
            self.inner.unary(req, path, codec).await
        }
        /// VerifyPassword returns whether a password matches a hash for a specific user.
        pub async fn verify_password(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyPasswordReq>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyPasswordResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/VerifyPassword");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "VerifyPassword"));
            self.inner.unary(req, path, codec).await
        }
        /// CreateConnector creates a connector.
        pub async fn create_connector(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateConnectorReq>,
        ) -> std::result::Result<
            tonic::Response<super::CreateConnectorResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/CreateConnector");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "CreateConnector"));
            self.inner.unary(req, path, codec).await
        }
        /// UpdateConnector updates a connector.
        pub async fn update_connector(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateConnectorReq>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateConnectorResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/UpdateConnector");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "UpdateConnector"));
            self.inner.unary(req, path, codec).await
        }
        /// DeleteConnector deletes a connector.
        pub async fn delete_connector(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteConnectorReq>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteConnectorResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/DeleteConnector");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "DeleteConnector"));
            self.inner.unary(req, path, codec).await
        }
        /// ListConnectors lists all connectors.
        pub async fn list_connectors(
            &mut self,
            request: impl tonic::IntoRequest<super::ListConnectorReq>,
        ) -> std::result::Result<
            tonic::Response<super::ListConnectorResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/ListConnectors");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "ListConnectors"));
            self.inner.unary(req, path, codec).await
        }
        /// GetVersion returns version information of the server.
        pub async fn get_version(
            &mut self,
            request: impl tonic::IntoRequest<super::VersionReq>,
        ) -> std::result::Result<tonic::Response<super::VersionResp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/GetVersion");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "GetVersion"));
            self.inner.unary(req, path, codec).await
        }
        /// ListRefresh lists all the refresh token entries for a particular user.
        pub async fn list_refresh(
            &mut self,
            request: impl tonic::IntoRequest<super::ListRefreshReq>,
        ) -> std::result::Result<
            tonic::Response<super::ListRefreshResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/ListRefresh");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "ListRefresh"));
            self.inner.unary(req, path, codec).await
        }
        /// RevokeRefresh revokes the refresh token for the provided user-client pair.
        pub async fn revoke_refresh(
            &mut self,
            request: impl tonic::IntoRequest<super::RevokeRefreshReq>,
        ) -> std::result::Result<
            tonic::Response<super::RevokeRefreshResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/api.Dex/RevokeRefresh");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("api.Dex", "RevokeRefresh"));
            self.inner.unary(req, path, codec).await
        }
    }
}
